---
title: "group2"
---

```{r}
#hussein mansour <hussein.mansour@tamu.edu>
#Xaoyu Li  <lxy819457986@tamu.edu>
#mohamed Zamani <mz154@tamu.edu>
# Libraries
#install.packages("fields")
#install.packages("MASS")
library(fields)  # for Matern and rdist functions
library(MASS)    # for rmvnorm function
```

```{r parameters to change}
#### you have to spatial_range (2 or 10) change the dimensions (1d or 2d).



# Set the range parameter for the exponential covariance function.
# This parameter determines the distance at which the correlation between two spatial points drops significantly.
# A smaller value of phi means the correlation drops off more rapidly with distance.
sigma = 1
phi = 1  ### parameter we are estimating 

# Set the damping parameter for the exponentially damped covariance function.
# This parameter determines the rate at which the correlation is damped.
# It's specifically used for the exponentially damped covariance function and not the standard exponential covariance.
sigma = 1
rho = 0.75  ### parameter we are estimating
gamma = 2


# Set the spatial range for generating data.
# This determines the range over which spatial data points are uniformly sampled.
spatial_range = 2 #or 10 #the range of spatial ... i.e [0,2] or [0,10] #######################################change spatitial range here#################################


# Data Generation
n = 100
coords = runif(n=100,0,spatial_range) # Uniform disturbution 1d ################################# choose dimensions here *1D* ##################################
#coords = cbind(runif(n,0,spatial_range),runif(n,0,spatial_range)) # for Uniform distribution 2d  ########################### or dimensions here *2D* ########################



D = rdist(coords) # Distance matrix
D 
```

```{r}
#The 0c(0;θ) function represents the covariance at lag 0 same for both exponential and damped exponential
c0_function  <- function(sigma) {
  return((sigma^2))
}

# Exponentially Covariance Function (subbing r= 1/Rg)
exp_cov  <- function(D, sigma, phi) {
  covariance <- (sigma^2) * exp(-D/(phi))
  return(covariance)
}

# Exponentially Damped Covariance Function
# The exponentially damped covariance function does not have  as a parameter; instead, it uses γ(or gamma)(the rate of decay) and ρ (or rho)(damping parameter)
exp_damped_cov <- function(D, sigma, gamma, rho) {
  covariance <- sigma^2 * exp(-gamma * D) * exp(-gamma^2 * D^2 / (2 * rho^2))
  return(covariance)
}
```

```{r } 
## Exponentially Covariance Function
### Given the parameters μ=5, σ^2 =1 and estimating phi :
vecchia_likelihood_exponetial <- function(params, z) {
  sigma = 1 #initialed equal to 1
  phi = params  # phi (params[2]) represents the practical range of the covariance function. 
  # It is the distance at which the correlation between two points drops to a specific threshold.
  # For instance, if phi is set to 2, it implies that the correlation between two points 
  # separated by a distance of 2 (or phi=2) is significantly reduced, often close to 0. 
  mu = 5 #  μ=5
 
  
  QV = 0
  for (i in 1:n) {
    if (i == 1) {
      neighbors = 1
    } else if (i == 2) {
      neighbors = 1:2
    } else {
      neighbors = (i-2):i
    }
    
    D_neighbors = matrix(D[neighbors, neighbors], nrow=length(neighbors), ncol=length(neighbors))
    Sigma = matrix(exp_cov(D_neighbors, sigma, phi), nrow=length(neighbors), ncol=length(neighbors))
    
    # Add a small nugget to the diagonal for regularization
    Sigma = Sigma + diag(1e-6, nrow=length(neighbors))
    #if(any(is.na(Sigma)) || any(is.infinite(Sigma))) {
    #  return(1e+6)  # Large positive value since we're minimizing
    #}
    
    Sigma_inv = ginv(Sigma)
    
    r = matrix(exp_cov(D[i, neighbors], sigma, phi), ncol=1)
    
    term1_value = c0_function(sigma) - t(r) %*% Sigma_inv %*% r
    
    # Check before taking log
    #if(term1_value <= 0) {
     # term1_value = 1e-6
    #}
    
    term1 = log(term1_value)
    
    term2_numerator = z[i] - mu - t(r) %*% Sigma_inv %*% matrix(z[neighbors] - mu, ncol=1)
    term2_denominator = c0_function(sigma) - t(r) %*% Sigma_inv %*% r
    term2 = term2_numerator^2 / term2_denominator
    
    QV = QV + term1 + term2
  }
  return(QV)
}
```

```{r } 
## Exponentially dapmed Covariance Function 
vecchia_likelihood_exponetial_dapmed <- function(params, z) {
  ### Given the parameters μ=5, γ=2, ρ=0.75, and σ^2 =1:
  #When optimizing the exponentially damped covariance function, you would typically optimize with respect to:
  #1. σ (or 2σ 2 ): To determine the best-fitting variance.
  #2.γ: To determine the best-fitting rate of decay of the correlation with distance.
  #3.ρ: To determine the best-fitting damping rate
  # here we are going to optimize using ρ (or rho)
  
  sigma = 1 # σ
  gamma = 2 # γ
  rho = params  # ρ
  mu = 5 #u
  QV = 0 
  for (i in 1:n) {
    if (i == 1) {
      neighbors = 1
    } else if (i == 2) {
      neighbors = 1:2
    } else {
      neighbors = (i-2):i
    }
    
    D_neighbors = matrix(D[neighbors, neighbors], nrow=length(neighbors), ncol=length(neighbors))
    Sigma = matrix(exp_damped_cov(D_neighbors, sigma, gamma, rho), nrow=length(neighbors), ncol=length(neighbors))
    
    # Add a small nugget to the diagonal for regularization
    Sigma = Sigma + diag(1e-6, nrow=length(neighbors))
    
    if(any(is.na(Sigma)) || any(is.infinite(Sigma))) {
      return(1e+6)  # Large positive value since we're minimizing
    }
    
    Sigma_inv = ginv(Sigma)
    
    r = matrix(exp_damped_cov(D[i, neighbors], sigma, gamma, rho), ncol=1)
    
    term1_value = c0_function(sigma) - t(r) %*% Sigma_inv %*% r
    
    term1 = log(term1_value)
    
    term2_numerator = z[i] - mu - t(r) %*% Sigma_inv %*% matrix(z[neighbors] - mu, ncol=1)
    term2_denominator = c0_function(sigma) - t(r) %*% Sigma_inv %*% r
    term2 = term2_numerator^2 / term2_denominator
    
    QV = QV + term1 + term2
  }
  return(QV)
}
```

```{r}
# Simulating Data and Estimating Parameters
num_simulations <- 400
results_matrix <- matrix(0, nrow=num_simulations, ncol=1)

for(sim in 1:num_simulations) {
  # Generate data
  sigma = 1 # σ

  Sigma = exp_cov(D, sigma, phi)
  # or Sigma = fields::Matern(D, nu=0.5, phi=phi) 
  z = rmvnorm(1, mu = rep(0,n), Sigma = Sigma)
  
  # Parameter estimation using Vecchia approximation likelihood
  initial_params <- c(phi) # phi
  
  #result = nlm(vecchia_likelihood_exponetial, initial_params, z=z , stepmax=5, print.level=2, gradtol=10^(-10))
  lower_bound <- 0  # Replace with your desired lower bound
  upper_bound <- 4  # Replace with your desired upper bound

  # Use optim with L-BFGS-B method
  result = optim(par = initial_params, 
                fn = vecchia_likelihood_exponetial, 
                method = "L-BFGS-B", 
                lower = lower_bound, 
                upper = upper_bound, 
                control = list(maxit = 10000,trace = 1), # Example max iterations
                z = z)
  
  # Store results
  results_matrix[sim] = result$par
}

print(results_matrix)

```

```{r}
# Histogram for phi

hist(results_matrix[, 1], main="Histogram for phi", xlab="Phi ϕ", col="lightyellow", border="black", breaks="Sturges")


```

```{r}
print(paste("exponential covariance Phi ϕ mean: ",mean(results_matrix[,1])) )
print(paste("exponential covariance Phi ϕ bais: ",mean(results_matrix[,1]) - phi))
print(paste("exponential covariance Phi ϕ std: ",sd(results_matrix[,1])))
```


```{r}
num_simulations <- 400
results_matrix <- matrix(0, nrow=num_simulations, ncol=1)

for(sim in 1:num_simulations) {
  # Given parameters
  sigma = 1 # σ
  gamma = 2 # γ
  rho = 0.75 # ρ

  # Generate the covariance matrix using the exp_damped_cov function
  Sigma = exp_damped_cov(D, sigma, gamma, rho)
  z = rmvnorm(1, mu = rep(0,n), Sigma = Sigma)
  
  # Parameter estimation using Vecchia approximation likelihood
  initial_params <- c(rho) # Initial guesses for sigma and Rg
  
  #result = nlm(vecchia_likelihood_exponetial, initial_params, z=z , stepmax=5, print.level=2, gradtol=10^(-10))
  lower_bound <- 0  # Replace with your desired lower bound
  upper_bound <- 1  # Replace with your desired upper bound

  # Use optim with L-BFGS-B method
  result = optim(par = initial_params, 
                fn = vecchia_likelihood_exponetial_dapmed, 
                method = "L-BFGS-B", 
                lower = lower_bound, 
                upper = upper_bound, 
                control = list(maxit = 10000,trace = 1), # Example max iterations
                z = z)
  
  # Store results
  results_matrix[sim] = result$par
}

print(results_matrix)
```



```{r}
# Histogram for sigma
hist(results_matrix[, 1], main="Histogram for rho", xlab="rho ρ", col="lightblue", border="black", breaks="Sturges")
```



```{r}
print(paste("exponential covariance rho ρ mean: ",mean(results_matrix[,1])) )
print(paste("exponential covariance rho ρ bais: ",mean(results_matrix[,1]) - rho))
print(paste("exponential covariance rho ρ std: ",sd(results_matrix[,1])))
```